# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mockups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('htmlCode', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
                ('description', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
