# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0003_auto_20160401_1350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mockups',
            new_name='Mockup',
        ),
    ]
