# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0004_auto_20160401_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockup',
            name='img',
            field=models.ImageField(null=True, upload_to=b'mockups'),
        ),
    ]
