# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yolo', '0005_mockup_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('htmlCode', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
                ('description', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('temporary', models.BooleanField(default=False)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
