# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0006_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='mockupId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yolo.Mockup'),
        ),
    ]
