# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0008_auto_20160402_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='cleanedHtml',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
