# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0009_template_cleanedhtml'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'templateImages')),
            ],
        ),
    ]
