# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0010_template_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='template_images',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yolo.Template'),
        ),
    ]
