SOCIAL_AUTH_TWITTER_KEY = 'QN6Oo26eNC3FafgaHLOWRaUwt'
SOCIAL_AUTH_TWITTER_SECRET = 'iv2mJih05ZJAigcWSM2qCjV20Ia5EB3hif1ez9MbL596M10pOg'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'
SOCIAL_AUTH_LOGIN_URL = '/sign-in'
